### PR TITLE
upgrade to corefx (netstandard1.1)

### PR DESCRIPTION
**Pull request by schulz3000**
also >= dotnet 4.0 still supported

### CODE REVIEW

**Comment by sjdirect** [comment]
Hi, I have no time to maintain this project. Please consider hosting the code/build if you would like support in .net core.

**Comment by schulz3000** [comment]
Hi @sjdirect 
to port your project abot to corefx you need nrobots as reference also ported. So because of this you maybe should consider to accept this PR

**Comment by sjdirect** [comment]
It's never as simple as just accepting a PR. Notice also that the build server failed, meaning it requires work to fix. Then if people have an issues with the new build in either environment, I have to handle that too. I have no time and likely will not be upgrading NRobots or Abot to .NET core anytime soon. That is why I am asking others for help.

**Comment by sjdirect** [comment]
[Made this announcement today...](https://groups.google.com/forum/#!topic/abot-web-crawler/CraWZURElkk)

**Comment by Kemyke** [comment]
The AppVeyour should be reconfigured. This PR looks good.

**Comment by sjdirect** [comment]
Hello, thanks for contributing however, I will not accept .net core upgrade pull requests to this repository. Please create another repository like nrobots-dotnet-core and another appveyor build for it that creates the nuget packages. I am unable to support any .net core supporting changes at this time or in any foreseeable future. The only solution is to create seperate repos/projects/builds for the .net core versions of Abot, NRobots, and Commoner and host support them on your own. I may become a contributer in the future.

**Comment by Kemyke** [comment]
Ok i created the project and merge schulz3000 and my PR. https://github.com/Kemyke/nrobots-dotnet-core

I also created an appveyor CI build for it and upload a package to nuget.org with the name "NRobotsCore".

Please feel free to review the code.

**Pull request closed without merging**
